### ISSUE TITLE
<systemID>/customers/?lookupParam=username returns all customers

### ISSUE THREAD

**Issue by eirsyl** [abakusbackup/abacash-api#150]
curl 'http://127.0.0.1:9000/2/customers/?lookupParam=username' -H 'authorization: Token d54f9200b680ff11eb1ffcb01a99bde2' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: nb' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Electron/1.3.4 Safari/537.36' -H 'content-type: application/json' -H 'Accept: _/_' -H 'If-None-Match: W/"1a9-kj3uaKZ9JCpzeoUonj3p9A"' -H 'Connection: keep-alive' -H 'x-abacash-application-version: 0.0.1' --compressed

**Comment by larseen** [comment]
Since you dont specify a parameter to lookup the express routes the request to get list route. Do you feel this is an undesired behaviour?
Would you rather get a an error telling you to specify a parameter?

**Comment by ekmartin** [comment]
larsen is throwing out systems altogether
