### ISSUE TITLE
Transactions for cache synchronization operations

### ISSUE THREAD

**Issue by hawkaa** [abakusbackup/abacash-api#24]
The client will cache data in case of connection loss. Once the connection is back up again, local transactions must be synchronized with API. However, this synchronization mechanism is different from the original, since it must allow users to get a negative balance. In addition, it must accept a list of transactions instead of single transactions.

We suggest adding a `sync` endpoint to transactions that accept a list of transactions and allows negative balance.

**Comment by ekmartin** [comment]
The client can't be offline anymore now I guess, so closing this.
